In [1]:
#BÀI1
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [2]:
#BÀI2
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.1334, 0.8110, 0.0805, 0.5173],
        [0.3830, 0.1639, 0.8301, 0.7873],
        [0.2827, 0.2061, 0.9536, 0.1339]])
tensor([[ 0.0416,  0.6624, -0.7309,  0.2387],
        [ 0.4754, -0.0657,  0.8742, -1.1453],
        [-0.7842, -0.4013,  0.6790,  1.9839]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [5]:
#BÀI3
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


In [6]:
#BÀI4
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[ 0.1758,  0.7572, -1.1925,  0.1885, -1.1569],
         [-0.3838, -1.5027, -1.0623,  1.5522, -0.6658],
         [ 0.1857,  0.6474, -0.2400, -0.9376,  1.4860],
         [ 0.5251, -1.2657,  1.0484,  0.6891, -0.3508]],

        [[ 0.9092,  0.0587,  0.7695,  0.2449,  0.0215],
         [ 1.1290,  0.4281,  0.5678,  2.0604, -1.1456],
         [-1.3122,  0.1422,  1.4138,  1.2961, -0.0981],
         [-0.4747, -0.1511,  0.7956,  0.8608,  0.9041]],

        [[-1.0872, -0.7267, -0.0389, -1.0960,  0.5225],
         [-1.1937,  0.1974, -1.1052,  0.0823,  0.4282],
         [ 1.1359,  1.1724, -0.7016, -0.8532,  0.5180],
         [ 0.4123,  0.5226,  1.8062, -0.2810, -0.3743]]])

Tensor a[1]:
tensor([[ 0.9092,  0.0587,  0.7695,  0.2449,  0.0215],
        [ 1.1290,  0.4281,  0.5678,  2.0604, -1.1456],
        [-1.3122,  0.1422,  1.4138,  1.2961, -0.0981],
        [-0.4747, -0.1511,  0.7956,  0.8608,  0.9041]])

Tensor a[1:, 2:4]:
tensor([[[-1.3122,  0.1422,  1.4138,  1.2961, -0.0

In [7]:
#BÀI5
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[-0.9587, -0.7550, -0.0617,  0.7407],
        [-0.3919, -0.4482,  0.2996, -0.6158],
        [-0.3479,  0.9870, -0.2089, -0.3845]])

Flatten:
tensor([-0.9587, -0.7550, -0.0617,  0.7407, -0.3919, -0.4482,  0.2996, -0.6158,
        -0.3479,  0.9870, -0.2089, -0.3845])

Reshape to 3 x 2 x 2:
tensor([[[-0.9587, -0.7550],
         [-0.0617,  0.7407]],

        [[-0.3919, -0.4482],
         [ 0.2996, -0.6158]],

        [[-0.3479,  0.9870],
         [-0.2089, -0.3845]]])


In [8]:
#BÀI6
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 0.0261, -1.4156,  0.9394],
        [-1.1134,  0.0670, -1.2912]])
b:
tensor([[-0.4302,  0.7147, -1.1430],
        [ 0.1196,  0.1268, -0.0134]])

a + b:
tensor([[-0.4041, -0.7009, -0.2036],
        [-0.9938,  0.1938, -1.3046]])

a / b:
tensor([[-6.0724e-02, -1.9808e+00, -8.2189e-01],
        [-9.3063e+00,  5.2872e-01,  9.6211e+01]])

a^2:
tensor([[6.8244e-04, 2.0038e+00, 8.8247e-01],
        [1.2397e+00, 4.4939e-03, 1.6671e+00]])

Matrix multiplication:
tensor([[-2.0966, -0.1890],
        [ 2.0027, -0.1074]])


In [9]:
#BÀI7
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[ 0.1240, -0.5989, -0.4126,  0.1690],
        [ 1.2239,  1.0182, -0.0662,  0.1255],
        [-0.4447, -0.4030,  2.8893,  0.9498]])

Mean:
tensor([0.3011, 0.0054, 0.8035, 0.4148])

Standard deviation:
tensor([0.8483, 0.8825, 1.8146, 0.4638])

Cumulative sum:
tensor([[ 0.1240, -0.5989, -0.4126,  0.1690],
        [ 1.3479,  0.4192, -0.4788,  0.2945],
        [ 0.9032,  0.0162,  2.4105,  1.2443]])


In [10]:
#BÀI8
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [13]:
#BÀI9
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

# In kết quả sau khi chạy xong 1000 vòng lặp
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-1.4317],
        [ 0.7673],
        [ 1.2414]], requires_grad=True)
Learned coefficients:
tensor([[0.9890],
        [2.0600],
        [3.5980]], requires_grad=True)


In [15]:
#BÀI10
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

# In kết quả sau khi kết thúc 2000 vòng lặp
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.2339, requires_grad=True)
B = tensor(4.7660, requires_grad=True)
C = tensor(3.7661, requires_grad=True)
D = tensor(2.7660, requires_grad=True)


In [1]:
#BÀI11
import torch
import numpy as np

# Yêu cầu 1: Khởi tạo và Reshape Tensor

X = torch.arange(24) # Tạo tensor 24 phần tử từ 0 đến 23
print("X shape ban đầu:", X.shape)

X_4x6 = X.reshape(4, 6)
print("\nReshape 4x6:\n", X_4x6)

X_2x12 = X.reshape(2, 12)
print("\nReshape 2x12:\n", X_2x12)

X_2x3x4 = X.reshape(2, 3, 4)
print("\nReshape 2x3x4:\n", X_2x3x4)


# Yêu cầu 2: Các phép toán cơ bản và thống kê

A = torch.rand(3, 4)
B = torch.rand(3, 4)
# Thêm số nhỏ vào B để tránh lỗi chia cho 0 nếu sinh ngẫu nhiên dính số 0
B = B + 1e-6 

print("\n--- Phép toán ---")
print("A + B:\n", A + B)
print("A * B:\n", A * B)
print("A / B:\n", A / B)

print("\n--- Thống kê theo cột (dim=0) ---")
print("Trung bình theo cột của A:\n", torch.mean(A, dim=0))
print("Độ lệch chuẩn theo cột của A:\n", torch.std(A, dim=0))


# Yêu cầu 3: Tính Autograd cho đa thức

x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5 * x + 3
y.backward()

print("\n--- Autograd ---")
print("Đạo hàm dy/dx (PyTorch):", x.grad.item())
# Tính thủ công: y' = 4x + 5. Tại x = 2 -> 4(2) + 5 = 13.
print("Đạo hàm tính thủ công: 13.0")

# Yêu cầu 4: Huấn luyện tìm đa thức

print("\n--- Tìm hệ số đa thức y = 2x^2 - 3x + 5 ---")
# Tạo dữ liệu thực tế dựa trên hàm y = 2x^2 - 3x + 5
polynomial_new = np.poly1d([2, -3, 5])
N = 100 # Tăng N lên để hội tụ chính xác hơn
X_np = np.random.randn(N, 1) * 5
Y_np = polynomial_new(X_np)

# Tạo ma trận đặc trưng
XX_np = np.hstack([X_np * X_np, X_np, np.ones_like(X_np)])

x_tensor = torch.tensor(XX_np, dtype=torch.float32)
y_tensor = torch.tensor(Y_np, dtype=torch.float32)

# Khởi tạo trọng số w cần học
w = torch.randn(3, 1, requires_grad=True)

# Dùng NAdam optimizer
optimizer = torch.optim.NAdam([w], lr=0.05)

for epoch in range(2000):
    optimizer.zero_grad()
    y_pred = x_tensor @ w
    mse = torch.mean(torch.square(y_tensor - y_pred))
    mse.backward()
    optimizer.step()

print("Hệ số thực tế: [2.0, -3.0, 5.0]")
print("Hệ số học được:\n", w.data.numpy().flatten())

X shape ban đầu: torch.Size([24])

Reshape 4x6:
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

Reshape 2x12:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

Reshape 2x3x4:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

--- Phép toán ---
A + B:
 tensor([[1.4032, 0.8930, 0.3974, 0.6178],
        [0.7116, 1.1447, 1.8417, 0.7998],
        [1.3604, 0.9376, 1.0412, 0.5616]])
A * B:
 tensor([[0.4347, 0.0547, 0.0161, 0.0131],
        [0.1199, 0.1792, 0.8479, 0.1428],
        [0.4626, 0.1637, 0.1544, 0.0700]])
A / B:
 tensor([[ 0.4906, 12.5021,  0.1302, 26.9932],
        [ 1.5979,  0.1955,  1.0144,  0.5071],
        [ 1.0257,  0.3287,  0.2077,  2.0026]])

--- Thống kê theo cột (dim=0) ---
Trung bình theo cột của A:
